### ISSUE TITLE
Full gradient should be averaged or not ?

### ISSUE THREAD

**Issue by invkrh** [wangshusen/SparkGiant#2]
I notice that is we use always full gradient in the paper without averaging. However, the following code seems to average the full gradient. 

https://github.com/wangshusen/SparkGiant/blob/90cf9d9f0ad7fa39a434e9a66eda752c3561b88b/src/main/
scala/logistic/Giant.scala#L148

How does it impact the result and the coverage bound ? Which is the right way to do ?
Thank you.

**Comment by wangshusen** [comment]
There is only one full gradient according to the mathematical derivation in the paper, and the code computes the full gradient. There isn't such a thing---full gradient with/without averaging. It's all about proper scaling.

Line 148 scales the gradient by n^{-1} because I don't normalize the local gradients. Otherwise, if the local gradients were normalized, then here the scaling would be m^{-1}.

**Comment by invkrh** [comment]
The scaling makes sense. Thank you.
